services:
  db:
    container_name: postgres_simple_bot
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: top_secret_postgres_simple_bot
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5552:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: